name: pmd-demonstrator
channels:
- conda-forge
dependencies:
- python =3.10
- ipykernel =6.28.0
- matplotlib =3.8.2
- pandas =2.1.4
- papermill =2.4.0
- pyiron_base =0.6.20
- rdflib =7.0.0
- requests =2.31.0
- scipy =1.11.4
- sparqlwrapper =2.0.0
- tabulate  =0.9.0
